"""mgl_shader and pybullet_body."""
import sys, os
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from build_help import build
from help_common import SIG, PLOT, INT, FLT, starter

# ----------------------------------------------------------------- mgl_shader
body = """Arbitrary GLSL in the scene chain, ShaderToy-compatible.

THE NODE:

mgl_shader   your own fragment shader, over the whole frame

TWO MODES, AND THEY ARE DIFFERENT JOBS:

generator      draws a full-screen quad with your shader. Nothing that came
               before is looked at - the shader makes the picture.
post_process   grabs what the chain has drawn SO FAR, hands it to the shader as
               iChannel0, and draws the result. This is where a filter goes.

Put a generator at the start of a chain and a post_process at the end. A
post_process with nothing before it has nothing to work on.

SHADERTOY CODE MOSTLY JUST WORKS:
If your source contains mainImage, the node wraps it with the ShaderToy uniforms
- iTime, iResolution, iFrame, iMouse, iChannel0 to 3, iTimeDelta - so a shader
copied from ShaderToy runs without editing.

If it does not contain mainImage, the source is used as written, with the uniform
declarations added if there is no #version line. So you can write plain GLSL and
still have the uniforms available.

That compatibility is the reason to reach for this node. There is an enormous
amount of published shader work that will run here directly.

FILE OR TEXT, AND auto_reload IS THE ONE TO USE:
'file' points at a .glsl on disk and 'auto_reload' watches it, so the picture
updates as you save from an editor. That loop - edit, save, look - is much
faster than pasting.

'shader_text' takes the source directly, which is fine for something short or
for a shader generated by the patch itself.

'status' reports compilation. A shader that fails to compile leaves the previous
one running rather than going black, so watch that outlet - a silent failure
looks exactly like a shader that did nothing.

THE UNIFORMS YOU DRIVE:
'iTime' and 'iMouse' are inlets, so they do not have to come from the clock and
the mouse. Feed iTime from a signal and the shader runs on your time rather than
the wall's - which is how you scrub, freeze, or run it from an audio envelope.

The extra channels take textures for the shader to sample.

SYNTAX:
mgl_shader

EXAMPLE:
mgl_shader

INPUTS and PARAMETERS:

mgl chain in:
The scene chain.

file / shader_text / reload / auto_reload:
Where the source comes from, and whether to watch it.

mode:
generator or post_process.

iTime / iMouse:
The standard uniforms, as inlets you can drive.

OUTPUTS: 

mgl chain out:
The chain, continued.

status:
Whether it compiled.

RELATED:
mgl_texture and the mgl pages for the rest of the scene chain.
mgl_smpl_mesh if what you want to draw is a body."""

demo = [
    {'key': 'ctx', 'init': 'mgl_context', 'pos': (30, 62), 'w': 300, 'h': 200},
    {'key': 'sh', 'init': 'mgl_shader', 'pos': (30, 285), 'w': 320, 'h': 300,
     'props': {'auto_reload': True}},
    {'key': 'c0', 'comment': True, 'text': 'point file at a .glsl and turn on\nauto_reload - then edit, save, look\nShaderToy code with mainImage in it is\nwrapped automatically and runs unedited',
     'pos': (30, 600)},

    {'key': 'l1', 'init': 'list', 'pos': (400, 285), 'w': 320, 'h': 42,
     'props': {'text in': '', 'font size': '24'}},
    {'key': 'c4', 'comment': True, 'text': 'WATCH THIS. A shader that fails to\ncompile leaves the previous one running\nrather than going black - so a silent\nfailure looks like a shader doing nothing',
     'pos': (400, 335)},

    {'key': 'sig', 'init': 'signal', 'pos': (400, 480), 'w': 129, 'h': 78,
     'props': SIG('saw', 8.0, 10.0, False)},
    {'key': 'c8', 'comment': True, 'text': 'iTime is an INLET - drive it from a\nsignal and the shader runs on your time\nrather than the clock: scrub, freeze,\nor run it from an audio envelope',
     'pos': (400, 575)},

    {'key': 'c12', 'comment': True, 'text': 'generator FIRST in a chain, post_process\nLAST - a post_process with nothing\nbefore it has nothing to work on',
     'pos': (30, 745)},
]
links = [('ctx', 'mgl_chain', 'sh', 'mgl chain in'),
         ('sh', 'status', 'l1', ''),
         ('sig', '', 'sh', 'iTime')]
print(build('mgl_shader', 'mgl_shader - your own GLSL', body, demo, links,
            demo_width=760, text_width=800, text_height=720))

# -------------------------------------------------------------- pybullet_body
body = """A physically simulated body, standing in for a real one.

THE NODE:

pybullet_body   a humanoid in a physics simulation

It loads a humanoid model into a Bullet physics world with gravity, and steps it
forward when you tell it to. Each step, the body falls, collides with the ground
and responds to whatever forces are on it.

WHAT IT IS FOR HERE:
Not games. It is a way to ask what a body would do - to check whether a pose is
physically possible, to see what forces a movement implies, or to let something
respond to a push rather than to a recording.

Because it is a real simulation, the answers include the parts you did not
author: a body that overbalances, a limb that swings past where it was aimed, the
floor pushing back.

'step' ADVANCES IT, AND YOU DECIDE WHEN:
Nothing moves until you step it. That is deliberate - it lets the simulation run
in lockstep with the patch rather than on its own clock, so the physics and
whatever is driving it stay in agreement.

Step it once per frame for real-time behaviour. Step it several times per frame
and it runs fast; step it rarely and it runs slow, in its own time rather than
becoming jerky.

'pelvis_position' and 'pelvis_orientation' PLACE THE BODY:
The root of the figure is driven rather than simulated - you say where the pelvis
is and which way it faces, and the rest hangs off it and responds. That is what
lets a captured performance drive a simulated body: the pelvis follows the
recording, and the limbs do what physics says.

The joints have force-torque sensors enabled where the model allows it, so what
comes back includes what the joints were having to do.

'pose_out' and 'position_out' report the result - where everything ended up after
the step, which is not necessarily where you asked it to be.

SYNTAX:
pybullet_body

EXAMPLE:
pybullet_body

INPUTS and PARAMETERS:

step:
Advance the simulation. Nothing happens until you do.

pelvis_position / pelvis_orientation:
Where the root of the body is, and which way it faces.

OUTPUTS: 

pose_out:
The joint angles after the step.

position_out:
Where the body ended up.

RELATED:
smpl_torque, which computes what a movement implies without simulating it.
smpl_body and gl_body to draw the result."""

demo = [
    {'key': 'met', 'init': 'metro 16', 'pos': (30, 62), 'w': 129, 'h': 70,
     'props': {'on': False, 'period': 16.0, 'units': 'milliseconds'}},
    {'key': 'tog', 'init': 'toggle', 'pos': (30, 140), 'w': 45, 'h': 42},
    {'key': 'c0', 'comment': True, 'text': 'step it once a frame for real time.\nNothing moves until you step it',
     'pos': (100, 140)},

    {'key': 'pb', 'init': 'pybullet_body', 'pos': (30, 210), 'w': 320, 'h': 300},
    {'key': 'c2', 'comment': True, 'text': 'the pelvis is DRIVEN, the rest is\nsimulated - so a recorded performance\ncan move the root while the limbs do\nwhat physics says',
     'pos': (30, 525)},

    {'key': 'take', 'init': 'smpl_take', 'pos': (400, 62), 'w': 300, 'h': 200},
    {'key': 'inf', 'init': 'info', 'pos': (400, 285), 'w': 260, 'h': 80},
    {'key': 'c6', 'comment': True, 'text': 'the pose AFTER the step - which is not\nnecessarily where you asked it to be.\nThat difference is the useful part:\noverbalancing, swinging past, the floor\npushing back',
     'pos': (400, 380)},

    {'key': 'gb', 'init': 'gl_body', 'pos': (400, 550), 'w': 300, 'h': 200},
    {'key': 'c11', 'comment': True, 'text': 'draw what the simulation decided',
     'pos': (400, 765)},
]
links = [('tog', '', 'met', 'on'),
         ('met', '', 'pb', 'step'),
         ('take', 'root_position', 'pb', 'pelvis_position'),
         ('pb', 'pose_out', 'inf', 'in'),
         ('pb', 'pose_out', 'gb', 'pose in')]
print(build('pybullet_body', 'pybullet_body - a body that falls over', body,
            demo, links, demo_width=740, text_width=800, text_height=700))
